prefixes_list = [
    "www", "www1", "www2", "www3", "web", "home", "site", "main",
    "app", "apps", "api", "api1", "api2", "service", "services", "server",
    "status", "support", "help", "portal", "dashboard", "dev", "development",
    "develop", "devel", "test", "testing", "qa", "uat", "stage", "staging",
    "sandbox", "demo", "preview", "beta", "alpha", "admin", "administrator",
    "admins", "manage", "management", "console", "control", "cp", "panel",
    "auth", "login", "signin", "sso", "oauth", "identity", "id", "account",
    "accounts", "mail", "email", "smtp", "imap", "pop", "webmail", "mx",
    "exchange", "newsletter", "ns", "ns1", "ns2", "dns", "dns1", "dns2",
    "router", "gateway", "proxy", "loadbalancer", "lb", "vpn", "remote", "rdp",
    "ssh", "ftp", "sftp", "db", "database", "mysql", "postgres", "postgresql",
    "sql", "mssql", "mongo", "mongodb", "redis", "storage", "files", "file",
    "upload", "uploads", "download", "downloads", "backup", "backups", "media",
    "static", "assets", "cdn", "monitor", "monitoring", "metrics", "status",
    "health", "logs", "logging", "grafana", "kibana", "prometheus", "cloud",
    "aws", "azure", "gcp", "docker", "k8s", "kubernetes", "jenkins", "git",
    "gitlab", "github", "internal", "intranet", "private", "secure", "prod",
    "production", "live", "devops", "ops", "internal-api", "blog", "news",
    "shop", "store", "forum", "community", "docs", "documentation", "wiki",
    "status", "mobile", "m", "beta", "old", "new", "legacy", "v1", "v2",
    "v3", "demo", "sandbox",
]
